version: "3.2"
services:
  bert_as_a_service:
    build: ./bert_as_a_service
    container_name: bert_as_a_service
  capstone:
    build: ./capstone 
    depends_on:
      - bert_as_a_service
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: /Users/admin/Documents/capstone_final/capstone/data
        target: /app/data